---
title: "Pre-process sc Kropski (GSE135893)"
output: html_notebook
editor_options: 
  chunk_output_type: console
---



```{r setup}

library(Matrix)
library(readr)
library(dplyr)
library(Rcpp)
library(Seurat)
library(ggplot2)
library(ggrepel)

knitr::opts_chunk$set(fig.width=8, fig.align="center")

```


### Load data
```{r data}

##### SCRNA LUNG DATA, Kropski cohort #####

# genes <- read_tsv("/mnt/dzl_bioinf/FibrOmics/data/scSEQ/Kropski_560492/pre_formatted/features.tsv.gz", col_names=F)
# cells <- read_tsv("/mnt/dzl_bioinf/FibrOmics/data/scSEQ/Kropski_560492/pre_formatted/barcodes.tsv.gz", col_names=F)
# counts <- readMM("/mnt/dzl_bioinf/FibrOmics/data/scSEQ/Kropski_560492/pre_formatted/matrix.mtx.gz")

# Read in counts data (33694 genes x 220213 cells)
countsKropski <- Read10X(data.dir="/mnt/dzl_bioinf/FibrOmics/data/scSEQ/Kropski_560492/pre_formatted/", gene.column=1, cell.column=1)
# Read in metadata (114396 cells only)
metadata <- read.csv("/mnt/dzl_bioinf/FibrOmics/data/scSEQ/Kropski_560492/pre_formatted/metadata.csv.gz", row.names=1)
head(metadata)

# Make sure counts data and metadata have common cells
commonCells <- colnames(countsKropski) %in% rownames(metadata)
table(commonCells)
countsKropski2 <- countsKropski[,commonCells] # 33694 genes x 114396 cells

# Create Seurat Object
temp <- CreateSeuratObject(counts=countsKropski2, meta.data=metadata, min.cells=5, min.features=350)
temp

# Make subset, only include IPF and control
temp2 <- subset(temp, subset = Diagnosis == c("IPF", "Control"))
temp2@meta.data <- droplevels(temp2@meta.data)

# saveRDS(temp, file="./Data/Lung_Kropski_not_processed.rds")
# saveRDS(temp2, file="./Data/Lung_Kropski_not_processed_subset.rds")

```


### Violin plots and scatter plots (subset data)
```{r}

VlnPlot(temp2, features="nFeature_RNA", pt.size=0) + NoLegend()
VlnPlot(temp2, features="nCount_RNA", pt.size=0) + NoLegend()
VlnPlot(temp2, features="percent.mt", pt.size=0) + NoLegend()
VlnPlot(temp2, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), group.by = "Diagnosis", ncol = 2, pt.size=0)


FeatureScatter(temp2, feature1 = "nCount_RNA", feature2 = "percent.mt", group.by="orig.ident", pt.size=0.1) + NoLegend()
FeatureScatter(temp2, feature1 = "nFeature_RNA", feature2 = "percent.mt", group.by="orig.ident", pt.size=0.1) + NoLegend()
FeatureScatter(temp2, feature1 = "nCount_RNA", feature2 = "nFeature_RNA", group.by="orig.ident", pt.size=0.1) + NoLegend()


```


### Filter
```{r}

temp2 <- subset(temp2, subset = nFeature_RNA > 1000 & nFeature_RNA < 3500 & percent.mt < 10)
temp2

```


### Normalize
```{r}

temp2 <- NormalizeData(temp2) # save in temp2[["RNA]]@data

```


### PCA and UMAP (subset data)
```{r}

temp2 <- ScaleData(temp2) # scaled data stored in temp2[["RNA"]]@scale.data

temp2 <- RunPCA(temp2, features=VariableFeatures(temp2))
VizDimLoadings(temp2, dims = 1:2, reduction = "pca") + NoLegend()
DimPlot(temp2, reduction = "pca") + NoLegend()
DimPlot(temp2, reduction = "pca", group.by="Diagnosis")
DimPlot(temp2, reduction = "pca", group.by="Status")

DimHeatmap(temp2, dims = 1:3, cells = 500, balanced = T)
DimHeatmap(temp2, dims = 4:6, cells = 500, balanced = T)
DimHeatmap(temp2, dims = 7:9, cells = 500, balanced = T)
DimHeatmap(temp2, dims = 10:12, cells = 500, balanced = T)
DimHeatmap(temp2, dims = 13:15, cells = 500, balanced = T)
ElbowPlot(temp2)

temp2 <- RunTSNE(temp2)
temp2 <- RunUMAP(temp2, reduction = "pca", dims = 1:20)
DimPlot(temp2, reduction="umap", split.by="Diagnosis", group.by="celltype", label=T, label.size=2.7, ncol=2, repel=T) + NoLegend() + ggtitle("")
DimPlot(temp2, reduction="umap", group.by="celltype", label=T, label.size=2.7, repel=T) + NoLegend() + ggtitle("Kropski scRNA-seq data")

# saveRDS(temp2, file="./Data/Lung_Kropski_processed_subset.rds")

```
