---
title: "Pre-process sc Kaminski (GSE136831)"
output: html_notebook
editor_options: 
  chunk_output_type: console
---


```{r}

library(Matrix)
library(readr)
library(dplyr)
library(Rcpp)
library(Seurat)
library(ggplot2)
library(ggrepel)

```


### Load data
```{r, eval=F}

##### SCRNA LUNG DATA, Kaminski cohort #####
genes <- read_tsv("./data/scSEQ/kaminski_GSE136831/features.tsv.gz", col_names=T)
cells <- read_tsv("./data/scSEQ/kaminski_GSE136831/barcodes.tsv.gz", col_names=F)
countsKaminski <- readMM("./data/scSEQ/kaminski_GSE136831/matrix.mtx.gz") # Read in counts data (45947 genes x 312928 cells)

# Read in metadata (312928 cells)
metadata <- read.table("./data/scSEQ/kaminski_GSE136831/metadata.txt.gz", header = T, row.names = 1)
head(metadata)

# Make cell IDs as column names and gene IDs rownames of counts matrix
rownames(countsKaminski) <- genes$HGNC_EnsemblAlt_GeneID
colnames(countsKaminski) <- cells$X1

# Create Seurat Object
temp <- CreateSeuratObject(counts=countsKaminski, min.cells=10, min.features=350)

metadata <- metadata[match(rownames(temp@meta.data), rownames(metadata)),]

temp[["orig.ident"]] <- metadata$Library_Identity
temp[["SampleID"]] <- metadata$Subject_Identity
temp[["Disease"]] <- metadata$Disease_Identity
temp[["nGene"]] <- metadata$nGene
temp[["nUMI"]] <- metadata$nUMI
temp[["percent.mt"]] <- PercentageFeatureSet(temp, pattern = "^MT-")
temp[["Subclass_CellType"]] <- metadata$Subclass_Cell_Identity
temp[["CellType"]] <- metadata$Manuscript_Identity
temp[["CellType_Category"]] <- metadata$CellType_Category

temp <- subset(temp, subset = CellType_Category != "Multiplet")
temp@meta.data <- droplevels(temp@meta.data)

# Make subset, only include IPF and control
temp2 <- subset(temp, subset = Disease != "COPD")
temp2@meta.data <- droplevels(temp2@meta.data)

#saveRDS(temp, file="/path/to/Deconvolution/Data/Lung_Kaminski_not_processed.rds")
#saveRDS(temp2, file="/path/to/Deconvolution/Data/Lung_Kaminski_not_processed_subset.rds")

```

```{r, echo=FALSE}

# read data, with IPF and control only
temp2 <- readRDS("/mnt/dzl_bioinf/calverom/Deconvolution/Data/Lung_Kaminski_not_processed_subset.rds")

```


### Violin plots and scatter plots (subset data)
```{r}

VlnPlot(temp2, features="nFeature_RNA", pt.size=0) + NoLegend() + geom_hline(yintercept=4500) + coord_flip(ylim=c(0,7500))
VlnPlot(temp2, features="nCount_RNA", pt.size=0) + NoLegend() + geom_hline(yintercept=15000) + coord_flip(ylim=c(0,25000))
VlnPlot(temp2, features="percent.mt", pt.size=0) + NoLegend() + geom_hline(yintercept=10) + coord_flip()


FeatureScatter(temp2, feature1 = "nCount_RNA", feature2 = "percent.mt", group.by="orig.ident", pt.size=0.1) + NoLegend()
FeatureScatter(temp2, feature1 = "nFeature_RNA", feature2 = "percent.mt", group.by="orig.ident", pt.size=0.1) + NoLegend()
FeatureScatter(temp2, feature1 = "nCount_RNA", feature2 = "nFeature_RNA", pt.size=0.1) + NoLegend()

```


### Filter
```{r}

temp2 <- subset(temp2, subset = nFeature_RNA < 4500 & percent.mt < 10 & nCount_RNA < 15000)
temp2

```

```{r}

VlnPlot(temp2, features="nFeature_RNA", pt.size=0) + NoLegend()
VlnPlot(temp2, features="nCount_RNA", pt.size=0) + NoLegend()
VlnPlot(temp2, features="percent.mt", pt.size=0) + NoLegend()

```

### Downsample
```{r}

Idents(temp2) <- temp@meta.data$CellType

set.seed(1995)
temp2_down <- subset(temp2, downsample=2000)
temp2_down

```


### Normalize data
```{r}

temp2_down <- NormalizeData(temp2_down) # saved in temp2_down[["RNA]]@data

```

### PCA and UMAP (subset data)
```{r}

temp2_down <- ScaleData(temp2_down) # scaled data stored in temp2_down[["RNA"]]@scale.data

temp2_down <- RunPCA(temp2_down, features=VariableFeatures(temp2_down))
VizDimLoadings(temp2_down, dims = 1:2, reduction = "pca") + NoLegend()
DimPlot(temp2_down, reduction = "pca") + NoLegend()
DimPlot(temp2_down, reduction = "pca", group.by="Disease")

DimHeatmap(temp2_down, dims = 1:3, cells = 500, balanced = T)
DimHeatmap(temp2_down, dims = 4:6, cells = 500, balanced = T)
DimHeatmap(temp2_down, dims = 7:9, cells = 500, balanced = T)
DimHeatmap(temp2_down, dims = 10:12, cells = 500, balanced = T)
DimHeatmap(temp2_down, dims = 13:15, cells = 500, balanced = T)
ElbowPlot(temp2_down)

temp2_down <- RunTSNE(temp2_down)
temp2_down <- RunUMAP(temp2_down, reduction = "pca", dims = 1:20)
DimPlot(temp2_down, reduction="umap", group.by="CellType", label=T, label.size=2.7, repel=T) + NoLegend() + ggtitle("")

#saveRDS(temp2_down, file="/mnt/dzl_bioinf/calverom/Deconvolution/Data/Lung_Kaminski_processed_subset_downsampled.rds")

```